version: "3.8"
services:
  web:
    build:
      context: .
    image: andreamatt/sxl_challenges:latest
    secrets:
      - ENV
    networks:
      - webnet

  nginx:
    image: nginx
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/nginx.template
    ports:
    - "8080:80"
    networks:
      - webnet
    depends_on:
      - web
    # environment:
    # - NGINX_HOST=foobar.com
    # - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

secrets:
  ENV:
    file: ./.env

networks:
  webnet:
