name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Run Typescript Checks
        run: yarn lint


  test_ts:
    environment: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}  
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Yarn install
      run: yarn install

    - name: Yarn test
      run: yarn test
      env:
        DB_TEST_URL: ${{ secrets.DB_TEST_URL }}
        NODE_ENV: test
        HTTP_PORT: 8080
        HTTPS_PORT: 8443


  build:
    needs: [lint, test_ts]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install packages
        run: yarn install

      - name: Compile typescript
        run: yarn tsc


  test_js:
    needs: build
    environment: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install packages
        run: yarn install

      - name: Compile typescript
        run: yarn tsc

      - name: Test javascript
        run: yarn test-js
        env:
          DB_TEST_URL: ${{ secrets.DB_TEST_URL }}
          NODE_ENV: test
          HTTP_PORT: 8080
          HTTPS_PORT: 8443
